services:
    web:
      image: odoo18_gomax
      build:
        context: .
      container_name: gomax_18
      ports:
        - "8069:8069"
      tty: true
      stdin_open: true 
      #command: odoo -d GoMax-18 -u ott_subscription
      volumes:
        - web-data-gomax_18:/var/lib/odoo
        - ../dependencias:/mnt/extra-addons/dependencias
        - ../gomax_addons:/mnt/extra-addons/gomax_addons
        - ../odoo-l10n-ecuador:/mnt/extra-addons/l10n_ecuador
        - ../config:/etc/odoo
    postgres:
      container_name: postgres_db
      image: postgres:14
      restart: always
      environment:
        - POSTGRES_USER=odoo
        - POSTGRES_PASSWORD=odoo18
        - POSTGRES_DB=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - "5448:5432"
      volumes:
        - db-data-gomax_18:/var/lib/postgresql/data

volumes:
  db-data-gomax_18:
  web-data-gomax_18:
